#                                                                                                             
#                                                                                                             
#                                                 @@@@@@@@@@@@@@                                              
#                                 @@@@@@@@@@@@@@@@@@          @@@@@@@@@@@@@@@                                 
#                            @@@@@@@@@@@@@      @@              @@      @@@@@@@@@@@@@                         
#                       @@@@@     @@@@        @@                  @@        @@@@     @@@@@                    
#                   @@@        @@@          @@                      @@         @@@        @@@                 
#                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              
#            @@@@          @@             @@                          @@            @@         @@@@           
#          @@@           @@              @@                            @@             @@          @@@         
#        @@@            @@               @@                            @@              @@           @@@       
#       @@                                                                                            @@      
#      @@                                                                                              @@     
#     @@            @@           @@         @@  @@           @@   @@@@@@@@@@@@  @@@        @@           @@    
#    @@             @@           @@         @@  @@@@       @@@@  @@@@@@  @@@@@@ @@@@@      @@            @@   
#    @              @@           @@         @@  @@@@@     @@@@@  @@@@@    @@@@@ @@  @@@    @@             @   
#    @              @@           @@         @@  @@  @@@  @@@ @@  @@@@      @@@@ @@    @@@@ @@             @   
#    @              @@           @@         @@  @@   @@@@@@  @@  @@@@@    @@@@@ @@      @@@@@             @   
#    @              @@@@@@@@@@@@ \@@@@@@@@@@@/  @@    @@@@   @@   @@@@@@@@@@@@  @@        %@@             @   
#    @@                                                                                                  @@   
#     @@                                                                                                @@    
#      @@              @@                @@                            @@                @@            @@     
#        @@             @@               @@                            @@               @@           @@       
#          @@            @@               @@                          @@               @@          @@         
#            @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@           
#               @@@         @@@            @@                        @@            @@         @@@             
#                  @@@         @@           @@                      @@          @@@        @@@                
#                     @@@@@      @@@          @@                  @@         @@@      @@@@@                   
#                          @@@@@@    @@@        @@              @@        @@@   @@@@@@                        
#                               @@@@@@@@@@@@@@    @@          @@    @@@@@@@@@@@@@                             
#                                            @@@@@@@@@@@@@@@@@@@@@@@@                                         
#                                                                                                             
#                                          ＵＮＩＴＥＤ ＩＮ 𝙎𝙀𝙑𝙀𝙍𝘼𝙉𝘾𝙀                                        
#
text-color=#d6e2ee
border-color=#6fb8e3
background-color=#1b2d40
